version: 0.0
os: linux
files:
  - source: .
    destination: /route-planning/source
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: aws/scripts/build.sh
      timeout: 180
  ApplicationStart:
    - location: aws/scripts/start.sh
      timeout: 3600
