version: 0.0
os: linux
files:
  - source: .
    destination: /route-planning/source
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 180
  AfterInstall:
    - location: scripts/build.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 3600
